version: 2.0
jobs:
  build_gcc_latest:
    docker:
      - image: gcc:7
    steps:
      - checkout
      - run:
          name: Set up
          command: |
            git submodule sync; git submodule update --init # initialize git submodules
            apt-get install cmake
            apt-get install libsfml-dev
            apt-get install libyaml-cpp-dev
            apt-get install libgtest-dev
            mkdir build && cd build && cmake .. && make
workflows:
  version: 2
  build_and_test:
    jobs:
      - build_gcc_latest
